// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4vk7_JIzeCWDLC5JTGZ8IV9L439_LmK8',
    appId: '1:865912326780:web:3e46cf876f0fe6e23fd7f9',
    messagingSenderId: '865912326780',
    projectId: 'chronikflutter',
    authDomain: 'chronikflutter.firebaseapp.com',
    storageBucket: 'chronikflutter.firebasestorage.app',
    measurementId: 'G-6B3P06JRK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG0eS89UiCEHIbU0PU2StqJGa15Xh-vbE',
    appId: '1:865912326780:android:c37ad074143246bc3fd7f9',
    messagingSenderId: '865912326780',
    projectId: 'chronikflutter',
    storageBucket: 'chronikflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwBYKvmj5CMK-nkQXh91u6NQFYlAG6qX0',
    appId: '1:865912326780:ios:cc73ce464c00ffdf3fd7f9',
    messagingSenderId: '865912326780',
    projectId: 'chronikflutter',
    storageBucket: 'chronikflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwBYKvmj5CMK-nkQXh91u6NQFYlAG6qX0',
    appId: '1:865912326780:ios:cc73ce464c00ffdf3fd7f9',
    messagingSenderId: '865912326780',
    projectId: 'chronikflutter',
    storageBucket: 'chronikflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4vk7_JIzeCWDLC5JTGZ8IV9L439_LmK8',
    appId: '1:865912326780:web:b54120eaf34bcfe53fd7f9',
    messagingSenderId: '865912326780',
    projectId: 'chronikflutter',
    authDomain: 'chronikflutter.firebaseapp.com',
    storageBucket: 'chronikflutter.firebasestorage.app',
    measurementId: 'G-99XLT437TS',
  );
}
